const $=s=>document.querySelector(s);const app=$('#app');
let route=location.hash.replace('#/','')||'home';let activePos='noun';let quizIndex=0,quizScore=0,answered=false;
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function shell(){document.querySelectorAll('[data-route]').forEach(b=>{b.classList.toggle('active',b.dataset.route===route);b.onclick=()=>go(b.dataset.route)});}
function go(r){route=r;location.hash='#/'+r;render();window.scrollTo({top:0,behavior:'smooth'})}
function render(){shell();({home:home,notes:notes,paragraphs:paragraphs,quiz:quiz}[route]||home)();}
function home(){app.innerHTML=`<section class="hero fade"><div><div class="eyebrow">University grammar • source-first notes</div><h1>Parts of<br><span style="opacity:.38">Speech.</span></h1><p class="lede">A clean, fast revision app built around your university notes, organised for quick study and quiz revision.</p><div style="margin-top:24px;display:flex;gap:9px;flex-wrap:wrap"><button class="primary" onclick="go('notes')">Open notes</button><button class="secondary" onclick="go('quiz')">Start quiz</button></div></div><div class="hero-card glass"><div><div class="eyebrow">Prepared for Talha</div><div class="big">${POS.length}</div><div style="font-size:18px;font-weight:650">parts of speech sections</div></div><div class="made">Made by Talha · black & white · glass blur UI</div></div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">Your syllabus map</div><h2>Everything in one place.</h2></div><p>Tap a section to open its types, definitions and examples. The wording follows the supplied university notes; where a point is incomplete, the app marks that clearly.</p></div><div class="grid">${POS.map((p,i)=>`<article class="card" onclick="activePos='${p.id}';go('notes')"><div class="card-num">0${i+1}</div><div class="card-title">${p.title}</div><div class="card-sub">${p.subtitle} · ${p.count}</div></article>`).join('')}</div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">Quick revision</div><h2>Quiz mode.</h2></div><p>Short questions are based on the same source-derived categories, so you can test yourself before your quiz.</p></div><div class="card" onclick="go('quiz')"><div class="card-title">12 questions · instant feedback</div><div class="card-sub">No sign-in. No internet required after the page is loaded.</div></div></section>`}
function notes(){const p=POS.find(x=>x.id===activePos)||POS[0];app.innerHTML=`<section class="fade"><div class="eyebrow">Study notes</div><h2>${p.title}</h2><p class="lede">${esc(p.intro)}</p><div class="tabs">${POS.map(x=>`<button class="tab ${x.id===p.id?'active':''}" onclick="activePos='${x.id}';notes()">${x.title}</button>`).join('')}</div><div class="list">${p.types.map((t,i)=>`<article class="item"><div class="item-top"><div><span class="pill">${String(i+1).padStart(2,'0')}</span><h3 style="margin-top:12px">${esc(t[0])}</h3></div><span style="color:var(--muted);font-size:12px">${esc(p.title)}</span></div><div class="definition">${esc(t[1])}</div><div class="examples">${t[2].split(', ').map(e=>`<span class="example">${esc(e)}</span>`).join('')}</div></article>`).join('')}</div>
<div class="section"><div class="section-head"><div><div class="eyebrow">Extra from the notebook</div><h2>Also written in your notes.</h2></div></div><div class="grid" style="grid-template-columns:repeat(2,1fr)">${EXTRA.map(e=>`<article class="card"><div class="card-title">${e.title}</div><div class="card-sub">${esc(e.text)}</div><div class="examples">${e.items.map(i=>`<span class="example">${esc(i)}</span>`).join('')}</div></article>`).join('')}</div></div>
</section>`}
function paragraphs(){const solvedIds=new Set(Object.keys(PARAGRAPH_SOLUTIONS));app.innerHTML=`<section class="fade"><div class="eyebrow">Applied examples</div><h2>Paragraph lab.</h2><p class="lede">Your supplied paragraphs are kept word-for-word, and now each exercise has a solved section underneath it. Use the raw paragraph first, then reveal the classification when revising.</p><input id="psearch" class="search" placeholder="Search paragraphs…"><div class="section list" id="plist">${PARAGRAPHS.map(p=>{const sol=PARAGRAPH_SOLUTIONS[p.id];return `<article class="item pitem"><div class="item-top"><div><span class="pill">source + solved</span><h3 style="margin-top:12px">${esc(p.title)}</h3></div></div><div class="paragraph">${esc(p.text)}</div><div class="raw-note" style="margin-top:16px">${esc(p.note)}</div>${sol?`<div class="solution-box"><div class="eyebrow">Solved answer</div><h3>${esc(sol.focus)}</h3><div class="solution-table">${sol.rows.map((r,i)=>`<div class="solution-row"><span class="solution-word">${esc(r[0])}</span><span class="solution-type">${esc(r[1])}</span>${r[2]?`<span class="solution-ref">${esc(r[2])}</span>`:''}</div>`).join('')}</div><div class="raw-note solution-note">${esc(sol.note)}</div></div>`:`<div class="raw-note">No solved table was added because the supplied material does not contain enough information to classify it safely.</div>`}</article>`}).join('')}</div><div class="section"><div class="section-head"><div><div class="eyebrow">Original supplied material</div><h2>Raw paragraph pages.</h2></div><p>The original source pages remain below so you can compare every solved answer with the material you were given.</p></div><div class="note-grid">${[1,2,3,4,5,6].map(n=>`<figure class="card gallery-card"><img class="note-img" src="assets/paragraphs/page-${String(n).padStart(2,'0')}.webp" alt="Supplied paragraph source page ${n}" loading="lazy"><figcaption class="gallery-caption">Source page ${n}</figcaption></figure>`).join('')}</div></div></section>`;$('#psearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.pitem').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?'block':'none')}}
function quiz(){if(quizIndex>=QUIZ.length){app.innerHTML=`<section class="quiz fade"><div class="quiz-card glass"><div class="eyebrow">Quiz complete</div><div class="score">${quizScore}/${QUIZ.length}</div><h2>Done.</h2><p class="lede">Review the Notes tab for anything you missed, then try again.</p><button class="primary" onclick="quizIndex=0;quizScore=0;answered=false;quiz()">Try again</button></div></section>`;return}const q=QUIZ[quizIndex];app.innerHTML=`<section class="quiz fade"><div class="quiz-card glass"><div style="display:flex;justify-content:space-between;color:var(--muted);font-size:13px"><span>Question ${quizIndex+1} of ${QUIZ.length}</span><span>Score ${quizScore}</span></div><div class="question">${esc(q[0])}</div><div class="options">${q[1].map(o=>`<button class="option" onclick="answer(this,'${o.replace(/'/g,"\\'")}','${q[2].replace(/'/g,"\\'")}')">${esc(o)}</button>`).join('')}</div><div id="feedback" style="min-height:24px;margin-top:15px;color:var(--muted)"></div><div class="quiz-actions"><button class="secondary" onclick="go('notes')">Review notes</button><button id="next" class="primary" disabled onclick="quizIndex++;answered=false;quiz()">Next</button></div></div></section>`}
function answer(btn,val,correct){if(answered)return;answered=true;document.querySelectorAll('.option').forEach(b=>{if(b.textContent===correct)b.classList.add('correct');else if(b!==btn)b.classList.add('wrong')});if(val===correct){quizScore++;$('#feedback').textContent='Correct.'}else $('#feedback').textContent=`Not quite — the source answer is “${correct}”.`;$('#next').disabled=false}
window.go=go;window.notes=notes;window.quiz=quiz;window.answer=answer;window.activePos=activePos;
$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('dark');localStorage.setItem('talha-theme',document.documentElement.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('talha-theme')==='dark')document.documentElement.classList.add('dark');
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
